
export const CURRENCY_LIST = [
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ' },
    { code: 'ALL', name: 'Albanian Lek', symbol: 'ALL' },
    { code: 'AMD', name: 'Armenian Dram', symbol: 'AMD' },
    { code: 'ARS', name: 'Argentine Peso', symbol: 'ARS' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
    { code: 'AWG', name: 'Aruban Florin', symbol: 'AWG' },
    { code: 'BBD', name: 'Barbadian Dollar', symbol: 'BBD' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: 'BDT' },
    { code: 'BMD', name: 'Bermudan Dollar', symbol: 'BMD' },
    { code: 'BND', name: 'Brunei Dollar', symbol: 'BND' },
    { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'BOB' },
    { code: 'BSD', name: 'Bahamian Dollar', symbol: 'BSD' },
    { code: 'BWP', name: 'Botswanan Pula', symbol: 'BWP' },
    { code: 'BZD', name: 'Belize Dollar', symbol: 'BZD' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
    { code: 'COP', name: 'Colombian Peso', symbol: 'COP' },
    { code: 'CRC', name: 'Costa Rican Colón', symbol: 'CRC' },
    { code: 'CUP', name: 'Cuban Peso', symbol: 'CUP' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'CZK' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'DKK' },
    { code: 'DOP', name: 'Dominican Peso', symbol: 'DOP' },
    { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'EGP' },
    { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB' },
    { code: 'EUR', name: 'Euro', symbol: '€' },
    { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJD' },
    { code: 'GBP', name: 'British Pound', symbol: '£' },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GHS' },
    { code: 'GIP', name: 'Gibraltar Pound', symbol: 'GIP' },
    { code: 'GMD', name: 'Gambian Dalasi', symbol: 'GMD' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'GTQ' },
    { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'GYD' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
    { code: 'HNL', name: 'Honduran Lempira', symbol: 'HNL' },
    { code: 'HRK', name: 'Croatian Kuna', symbol: 'HRK' },
    { code: 'HTG', name: 'Haitian Gourde', symbol: 'HTG' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'HUF' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'IDR' },
    { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
    { code: 'JMD', name: 'Jamaican Dollar', symbol: 'JMD' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KES' },
    { code: 'KGS', name: 'Kyrgystani Som', symbol: 'KGS' },
    { code: 'KHR', name: 'Cambodian Riel', symbol: 'KHR' },
    { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'KYD' },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: 'KZT' },
    { code: 'LAK', name: 'Laotian Kip', symbol: 'LAK' },
    { code: 'LBP', name: 'Lebanese Pound', symbol: 'LBP' },
    { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'LKR' },
    { code: 'LRD', name: 'Liberian Dollar', symbol: 'LRD' },
    { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL' },
    { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD' },
    { code: 'MDL', name: 'Moldovan Leu', symbol: 'MDL' },
    { code: 'MKD', name: 'Macedonian Denar', symbol: 'MKD' },
    { code: 'MMK', name: 'Myanmar Kyat', symbol: 'MMK' },
    { code: 'MNT', name: 'Mongolian Tugrik', symbol: 'MNT' },
    { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP' },
    { code: 'MUR', name: 'Mauritian Rupee', symbol: 'MUR' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR' },
    { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MWK' },
    { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'MYR' },
    { code: 'NAD', name: 'Namibian Dollar', symbol: 'NAD' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: 'NGN' },
    { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'NIO' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'NOK' },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: 'NPR' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
    { code: 'PAB', name: 'Panamanian Balboa', symbol: 'PAB' },
    { code: 'PEN', name: 'Peruvian Nuevo Sol', symbol: 'PEN' },
    { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'PGK' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: 'PKR' },
    { code: 'QAR', name: 'Qatari Rial', symbol: 'QAR' },
    { code: 'RUB', name: 'Russian Ruble', symbol: 'RUB' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR' },
    { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SCR' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'SEK' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
    { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'SLL' },
    { code: 'SOS', name: 'Somali Shilling', symbol: 'SOS' },
    { code: 'SSP', name: 'South Sudanese Pound', symbol: 'SSP' },
    { code: 'SVC', name: 'Salvadoran Colón', symbol: 'SVC' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TTD' },
    { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$' },
    { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS' },
    { code: 'USD', name: 'US Dollar', symbol: '$' },
    { code: 'UYU', name: 'Uruguayan Peso', symbol: 'UYU' },
    { code: 'UZS', name: 'Uzbekistan Som', symbol: 'UZS' },
    { code: 'YER', name: 'Yemeni Rial', symbol: 'YER' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'ZAR' }
  ];
  
  export const getCurrencySymbol = (currencyCode) => {
    const currency = CURRENCY_LIST.find(curr => curr.code === currencyCode);
    return currency ? currency.symbol : currencyCode;
  };
  
  export const getCurrencyName = (currencyCode) => {
    const currency = CURRENCY_LIST.find(curr => curr.code === currencyCode);
    return currency ? currency.name : currencyCode;
  };
  
  export const getFullCurrencyInfo = (currencyCode) => {
    return CURRENCY_LIST.find(curr => curr.code === currencyCode);
  };